// RecarregaAi! 2.5.0 — Elementos das configurações

export const optionsElements = {
  advancedCleanupInput: document.querySelector("#advanced-cleanup-input"),
  addSiteButton: document.querySelector("#add-site-button"),
  clearHistoryButton: document.querySelector("#clear-history-button"),
  closeOptionsButton: document.querySelector("#close-options-button"),
  collapseHistoryButton: document.querySelector("#collapse-history-button"),
  defaultIntervalInput: document.querySelector("#default-interval-input"),
  extensionVersion: document.querySelector("#extension-version"),
  exportSettingsButton: document.querySelector("#export-settings-button"),
  exportDiagnosticsButton: document.querySelector("#export-diagnostics-button"),
  importSettingsButton: document.querySelector("#import-settings-button"),
  importSettingsInput: document.querySelector("#import-settings-input"),
  historyCount: document.querySelector("#history-count"),
  historyEmptyState: document.querySelector("#history-empty-state"),
  historyFilterButtons: document.querySelectorAll("[data-history-filter]"),
  historyList: document.querySelector("#history-list"),
  historyPagination: document.querySelector("#history-pagination"),
  historyVisibleCount: document.querySelector("#history-visible-count"),
  optionsStatus: document.querySelector("#options-status"),
  operatingHoursEnabled: document.querySelector("#operating-hours-enabled"),
  operatingHoursFields: document.querySelector("#operating-hours-fields"),
  operatingStartTime: document.querySelector("#operating-start-time"),
  operatingEndTime: document.querySelector("#operating-end-time"),
  operatingWeekdays: document.querySelectorAll("[name='operating-weekday']"),
  preserveScrollInput: document.querySelector("#preserve-scroll-input"),
  playSoundInput: document.querySelector("#play-sound-input"),
  debugModeInput: document.querySelector("#debug-mode-input"),
  saveSettingsButton: document.querySelector("#save-settings-button"),
  showMoreHistoryButton: document.querySelector("#show-more-history-button"),
  siteFormAlert: document.querySelector("#site-form-alert"),
  siteFormAlertText: document.querySelector("#site-form-alert-text"),
  siteIntervalInput: document.querySelector("#site-interval-input"),
  siteOriginInput: document.querySelector("#site-origin-input"),
  sitesEmptyState: document.querySelector("#sites-empty-state"),
  sitesList: document.querySelector("#sites-list"),
  systemThemeInput: document.querySelector("#system-theme-input"),
  themeToggleButton: document.querySelector("#theme-toggle-button"),
  themeToggleLabel: document.querySelector("#theme-toggle-label")
};
